# Generated by Django 4.2.5 on 2023-10-05 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
