# Generated by Django 4.2.5 on 2023-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0007_book_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created"]},
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="book_book_author_33a3f1_idx"),
        ),
    ]
