# Generated by Django 4.2.5 on 2023-10-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0008_alter_book_options_book_book_book_author_33a3f1_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["cat_name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["bookid", "slug"], name="book_book_bookid_f56625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["-created"], name="book_book_created_be3f7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["cat_name"], name="book_catego_cat_nam_5ecedf_idx"
            ),
        ),
    ]
