# Generated by Django 4.2.5 on 2023-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0011_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
