# Generated by Django 4.2.5 on 2023-12-30 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0016_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user_liked",
            field=models.ManyToManyField(
                blank=True, related_name="review_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
