# Generated by Django 4.2.5 on 2023-12-30 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0017_review_user_liked"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
