# Generated by Django 4.2.5 on 2024-01-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
        ("book", "0018_delete_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authorid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="author.author",
            ),
        ),
    ]
