# Generated by Django 4.2.5 on 2024-01-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0019_book_authorid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
