# Generated by Django 4.2.5 on 2024-01-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
        ("book", "0020_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authorid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to="author.author",
            ),
        ),
    ]
