# Generated by Django 4.2.5 on 2023-10-28 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.RemoveField(
            model_name="order",
            name="street",
        ),
    ]
