# Generated by Django 4.2.5 on 2023-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_apartment_remove_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
