# Generated by Django 4.2.5 on 2023-11-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_shippingaddress_main"),
        ("orders", "0004_order_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.shippingaddress",
            ),
        ),
    ]
