# Generated by Django 4.2.5 on 2024-01-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_shippingaddress_postal_code"),
        ("orders", "0007_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.shippingaddress",
            ),
        ),
    ]
