# Generated by Django 4.2.5 on 2024-01-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_shippingaddress_country_and_more"),
        ("orders", "0008_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.shippingaddress"
            ),
        ),
    ]
