# Generated by Django 4.2.5 on 2023-10-28 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0002_remove_profile_apartment_remove_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
