# Generated by Django 4.2.5 on 2023-10-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_apartment_remove_order_city_and_more"),
        ("user", "0004_alter_profile_options_alter_shippingaddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_addresses",
                to="orders.order",
            ),
        ),
    ]
