# Generated by Django 4.2.5 on 2023-11-08 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_shippingaddress_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
    ]
