# Generated by Django 4.2.5 on 2023-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_remove_shippingaddress_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="main",
            field=models.BooleanField(default=True),
        ),
    ]
