# Generated by Django 4.2.5 on 2023-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_shippingaddress_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="main",
            field=models.BooleanField(),
        ),
    ]
