# Generated by Django 4.2.5 on 2023-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_shippingaddress_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="main",
            field=models.BooleanField(
                default=False, verbose_name="Main Shipping Address"
            ),
        ),
    ]
