# Generated by Django 4.2.5 on 2023-11-23 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_shippingaddress_apartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="postal_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Postal code must be in the format 00-000",
                        regex="^\\d{2}-\\d{3}$",
                    )
                ],
                verbose_name="Postal Code",
            ),
        ),
    ]
