# Generated by Django 4.2.5 on 2023-12-10 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_shippingaddress_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="postal_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Postal code must be in the 00-000 format",
                        regex="^\\d{2}-\\d{3}$",
                    )
                ],
                verbose_name="Postal Code",
            ),
        ),
    ]
