# Generated by Django 4.2.5 on 2024-01-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("surname", models.CharField(max_length=250)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="author_photos/"
                    ),
                ),
                ("own_url_page", models.URLField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["surname"],
                "indexes": [
                    models.Index(fields=["slug"], name="author_auth_slug_7559a6_idx"),
                    models.Index(
                        fields=["name", "surname"], name="author_auth_name_0c9522_idx"
                    ),
                    models.Index(
                        fields=["created"], name="author_auth_created_e3cba6_idx"
                    ),
                ],
            },
        ),
    ]
