# Generated by Django 4.2.5 on 2024-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="author_photos/%Y/%m/%d/"
            ),
        ),
    ]
